name = "saint-central-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Enable Node.js compatibility for PostgreSQL and crypto APIs
compatibility_flags = ["nodejs_compat"]

# Define KV namespace for rate limiting and security logs
kv_namespaces = [
  { binding = "SAINT_CENTRAL_KV", id = "bf3f14f5f3814e128b8b9e5ed8430299" }
]

# Non-sensitive environment variables (sensitive ones go in dashboard)
[vars]
# Security Configuration
MAX_LOGIN_ATTEMPTS = "5"
LOGIN_LOCKOUT_DURATION = "900000"
PASSWORD_MIN_LENGTH = "12"
RATE_LIMIT_ENABLED = "true"
BLOCKED_COUNTRIES = "CN,RU,KP,IR,SY,BY"
SESSION_TIMEOUT = "86400000"

# Database Performance Settings
DB_POOL_SIZE = "10"
DB_CONNECTION_TIMEOUT = "30000"
DB_QUERY_TIMEOUT = "60000"

# Monitoring & Logging
LOG_LEVEL = "info"
ENABLE_METRICS = "true"
ENABLE_TRACING = "true"

# CORS Configuration (update with your domains)
ALLOWED_ORIGINS = "*"

# Optional: Your Supabase URL (not sensitive - can be public)
# SUPABASE_URL = "https://your-project-id.supabase.co"

# Development environment
[env.dev]
name = "saint-central-worker-dev"

[env.dev.vars]
# Development-specific overrides
MAX_LOGIN_ATTEMPTS = "10"
PASSWORD_MIN_LENGTH = "8"
RATE_LIMIT_ENABLED = "false"
LOG_LEVEL = "debug"
BLOCKED_COUNTRIES = ""
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000"

# Staging environment
[env.staging]
name = "saint-central-worker-staging"

[env.staging.vars]
# Staging-specific overrides
MAX_LOGIN_ATTEMPTS = "7"
PASSWORD_MIN_LENGTH = "10"
LOG_LEVEL = "info"
ALLOWED_ORIGINS = "https://staging.yourdomain.com"

# Production environment
[env.production]
name = "saint-central-worker"

[env.production.vars]
# Production-specific overrides (most restrictive)
MAX_LOGIN_ATTEMPTS = "5"
PASSWORD_MIN_LENGTH = "12"
RATE_LIMIT_ENABLED = "true"
LOG_LEVEL = "warn"
BLOCKED_COUNTRIES = "CN,RU,KP,IR,SY,BY,MM,AF"
ALLOWED_ORIGINS = "https://yourdomain.com,https://app.yourdomain.com"

# Optional: Custom routes for production domain
# [env.production.routes]
# pattern = "api.saintcentral.com/*"
# zone_name = "saintcentral.com"

# Build configuration
[build]
command = "npm install"

# Required dependencies
[build.upload]
format = "modules"

# Optional: External packages configuration
# [build.upload.externals]
# packages = ["@neondatabase/serverless"]